apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: kanban-pod
  template:
    metadata:
      labels:
        app: kanban-pod
    spec:
      containers:
        - name: kanban-pod
          image: nananainfra1/kanban:v1
          ports:
            - containerPort: 80