apiVersion: v1
kind: Service
metadata:
  name: kanban-svc-node
spec:
  type: NodePort
  selector:
    app: kanban-pod
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30003